#!/bin/bash
# EC2-1 (Wazuh Manager all-in-one) userdata.
# Installs Wazuh 4.7 manager + indexer + dashboard via the official all-in-one
# installer. Ubuntu 22.04 LTS (amd64). Needs >=4GB RAM (indexer is memory-hungry);
# m7i-flex.large gives 8GB. Runs unattended; writes a done marker.
#
# Verified on a demo account / region, 2026-06-30: manager/indexer/dashboard
# all active, dashboard :443 -> 302 login, API :55000 -> 401 (auth required).
#
# Admin password is GENERATED by the installer into /root/wazuh-install-files.tar
# (wazuh-passwords.txt). It is NOT printed here and NOT committed. Pull it once,
# store in a secret manager, and rotate before any non-lab use.
set -x
exec > /var/log/wazuh-bootstrap.log 2>&1
export DEBIAN_FRONTEND=noninteractive

apt-get update -y
apt-get install -y curl apt-transport-https unzip wget

cd /root
curl -sO https://packages.wazuh.com/4.7/wazuh-install.sh
chmod +x wazuh-install.sh
# -a = all-in-one (manager+indexer+dashboard on one host); -i = ignore HW check (lab)
./wazuh-install.sh -a -i 2>&1

echo "WAZUH_INSTALL_DONE rc=$?" > /var/log/wazuh-install-done.marker

# --- 告警外发:把 alerts.json 推到 CloudWatch Logs(独立留存,防 manager 本地单点丢失) ---
# 占位符由 setup-wazuh-two-ec2.sh 在 launch 前 sed 注入(空=未配则跳过,向后兼容)。
# 解决"告警只躺 manager 本地、那台 EC2 没了就全丢"的问题:alerts.json 实时镜像到
# 独立 log group,manager 被删/被攻陷删本地日志,CloudWatch 那份仍在(可再叠 S3+Object
# Lock 做 WORM 防删,见 RUNBOOK)。需要 manager instance role 的 logs:PutLogEvents 权限。
ALERTS_LOG_GROUP="__ALERTS_LOG_GROUP__"
AWS_REGION_CFG="__AWS_REGION__"
if [ "$ALERTS_LOG_GROUP" != "__ALERTS_LOG_GROUP__" ] && [ -n "$ALERTS_LOG_GROUP" ]; then
  echo "configuring CloudWatch agent to ship alerts.json -> $ALERTS_LOG_GROUP"
  curl -sO https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
  dpkg -i -E amazon-cloudwatch-agent.deb || apt-get install -f -y
  mkdir -p /opt/aws/amazon-cloudwatch-agent/etc
  cat > /opt/aws/amazon-cloudwatch-agent/etc/cw-alerts.json <<CWCFG
{
  "agent": { "region": "${AWS_REGION_CFG}" },
  "logs": { "logs_collected": { "files": { "collect_list": [
    {
      "file_path": "/var/ossec/logs/alerts/alerts.json",
      "log_group_name": "${ALERTS_LOG_GROUP}",
      "log_stream_name": "{instance_id}/alerts",
      "retention_in_days": 30
    }
  ] } } }
}
CWCFG
  /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
    -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/cw-alerts.json || true
  echo "CW_AGENT_DONE" >> /var/log/wazuh-install-done.marker
else
  echo "ALERTS_LOG_GROUP unset — alerts stay LOCAL ONLY (manager-local single point of loss; set up CloudWatch shipping for prod)" >> /var/log/wazuh-install-done.marker
fi

# --- Real-time FIM + whodata on the MANAGER's own /etc (optional; mirrors the
#     reference article so the manager also self-monitors). The PRIMARY FIM target
#     in this two-EC2 design is the AGENT node — see agent-userdata.sh. ---
# (Left commented by default: the manager box runs the SIEM stack and you usually
#  monitor endpoints, not the SIEM host. Uncomment to also watch the manager.)
#
# python3 /root/apply-realtime-fim.py /var/ossec/etc/ossec.conf || true
# systemctl restart wazuh-manager
