[SERVICE]
    flush        5
    storage.path ${FB_STORAGE_DIR}

[INPUT]
    Name             tail
    Path             /var/log/nginx/access.log
    Tag              edge.access

@INCLUDE outputs.conf
