#!/usr/bin/env bash
# aos-bootstrap.sh — one-time bootstrap of the claw-logs AOS domain.
#
# CDK cannot express OpenSearch security-plugin objects (index templates,
# ISM policies, FGAC role mappings). This script puts them via the domain's
# `_plugins/_security` and `_index_template` / `_plugins/_ism/policies`
# REST APIs. Idempotent — safe to re-run after every stack update.
#
# When to run: after `cdk deploy` finishes and CfnOutput `LogDomainEndpoint`
# is populated. Run from inside the VPC (bastion / any host with reach to
# the domain SG) since the domain is VPC-only.
#
# Auth: SigV4 as the caller's IAM identity. The IAM identity used to run
# this script MUST be mapped as the AOS master (or have an FGAC role
# giving `_security` write) — the CDK creates the domain with an internal
# user database master, so the first bootstrap MUST use the master
# username/password stored in Secrets Manager (auto-generated by CDK).
# After that, prefer SigV4 as an assumed IAM role (see aws-cli --profile).
#
# Contract: fails loud on any non-2xx response.

set -euo pipefail

AOS_ENDPOINT="${AOS_ENDPOINT:?AOS_ENDPOINT required (from CfnOutput LogDomainEndpoint, no scheme)}"
AOS_ADMIN_USER="${AOS_ADMIN_USER:-claw-logs-admin}"
AOS_ADMIN_PASS="${AOS_ADMIN_PASS:?AOS_ADMIN_PASS required — fetch from Secrets Manager}"
FIREHOSE_ROLE_ARN="${FIREHOSE_ROLE_ARN:?FIREHOSE_ROLE_ARN required (from stack outputs)}"

curl_aos() {
    local method="$1"; shift
    local path="$1"; shift
    curl -sS -u "${AOS_ADMIN_USER}:${AOS_ADMIN_PASS}" \
        -X "${method}" \
        -H 'Content-Type: application/json' \
        --fail-with-body \
        "https://${AOS_ENDPOINT}${path}" "$@"
}

# 1. Index template: pin field types for claw-logs-* indices.
#    trace_root MUST be keyword (join key); refresh_interval 30s to keep
#    write-heavy edge log ingestion cheap; ignore_malformed so a single
#    bad `-` in a numeric field doesn't drop the whole doc.
curl_aos PUT '/_index_template/claw-logs' -d '{
  "index_patterns": ["claw-logs-*"],
  "template": {
    "settings": {
      "index.refresh_interval": "30s",
      "index.number_of_shards": 1,
      "index.number_of_replicas": 1,
      "index.codec": "best_compression",
      "index.mapping.ignore_malformed": true
    },
    "mappings": {
      "properties": {
        "time":         {"type": "date"},
        "service":      {"type": "keyword"},
        "level":        {"type": "keyword"},
        "trace_root":   {"type": "keyword"},
        "tenant_id":    {"type": "keyword"},
        "tenant_name":  {"type": "keyword"},
        "launch_id":    {"type": "keyword"},
        "status":       {"type": "short"},
        "request_method":{"type": "keyword"},
        "request_uri":  {"type": "text",
                         "fields": {"keyword": {"type": "keyword", "ignore_above": 256}}},
        "request_time": {"type": "float"},
        "remote_addr":  {"type": "ip"},
        "user_agent":   {"type": "text",
                         "fields": {"keyword": {"type": "keyword", "ignore_above": 256}}},
        "msg":          {"type": "text"}
      }
    }
  }
}'

# 2. ISM policy: age-based (no rollover — Firehose OneDay rotation is the
#    rotation mechanism, see design.md §6). hot → warm (replica 0 +
#    read_only) at 7d → delete at 30d.
curl_aos PUT '/_plugins/_ism/policies/claw-logs-lifecycle' -d '{
  "policy": {
    "description": "claw-logs age-based lifecycle: hot 7d → warm 30d delete",
    "default_state": "hot",
    "states": [
      {
        "name": "hot",
        "transitions": [
          {"state_name": "warm", "conditions": {"min_index_age": "7d"}}
        ]
      },
      {
        "name": "warm",
        "actions": [
          {"replica_count": {"number_of_replicas": 0}},
          {"read_only": {}}
        ],
        "transitions": [
          {"state_name": "delete", "conditions": {"min_index_age": "30d"}}
        ]
      },
      {
        "name": "delete",
        "actions": [{"delete": {}}]
      }
    ],
    "ism_template": [
      {"index_patterns": ["claw-logs-*"], "priority": 100}
    ]
  }
}'

# 3. FGAC: create a scoped role for the Firehose delivery IAM role.
#    `_bulk` is a cluster-level action — MUST be granted at cluster_permissions.
#    Index writes scoped to claw-logs-*.
curl_aos PUT '/_plugins/_security/api/roles/claw-logs-firehose-writer' -d '{
  "cluster_permissions": ["cluster_composite_ops"],
  "index_permissions": [
    {
      "index_patterns": ["claw-logs-*"],
      "allowed_actions": ["write", "create_index"]
    }
  ]
}'

# 4. Map the Firehose IAM role to the scoped AOS role (backend_roles).
curl_aos PUT '/_plugins/_security/api/rolesmapping/claw-logs-firehose-writer' -d "{
  \"backend_roles\": [\"${FIREHOSE_ROLE_ARN}\"]
}"

echo "aos-bootstrap: OK"
